CREATE TABLE contract (
    id_contract NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_artist NUMBER,
    id_label NUMBER,
    data_start DATE,
    data_incheiere DATE,
    CONSTRAINT fk_contract_artist FOREIGN KEY (id_artist) REFERENCES artist(id_artist),
    CONSTRAINT fk_contract_label FOREIGN KEY (id_label) REFERENCES label(id_label)
);