CREATE TABLE gen_muzical (
    id_gen NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nume_gen VARCHAR2(50) CONSTRAINT gen_muzical_nume_gen_nn NOT NULL
);

CREATE TABLE album (
    id_album NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    titlu VARCHAR2(100) CONSTRAINT album_titlu_nn NOT NULL,
    data_lansare DATE,
    id_artist NUMBER,
    id_gen NUMBER,
    CONSTRAINT fk_album_gen FOREIGN KEY (id_gen) REFERENCES gen_muzical(id_gen)
);