-- ARTIST
CREATE TABLE artist (
    id_artist NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nume_scena VARCHAR2(50) CONSTRAINT artist_nume_scena_nn NOT NULL,
    CONSTRAINT artist_nume_scena_uk UNIQUE (nume_scena),
    nume_real VARCHAR2(100),
    data_nasterii DATE,
    tara_origine VARCHAR2(50) DEFAULT 'Necunoscut' CONSTRAINT artist_tara_origine_nn NOT NULL
);

COMMIT;



