server:
  port: 8888


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/biancapaun/config-repo
          default-label: main
